[phases.setup]
nixPkgs = ["nodejs", "python3", "python3Packages.pip", "python3Packages.virtualenv"]

[phases.install]
cmds = [
    "python3 -m venv /opt/venv",
    "source /opt/venv/bin/activate && pip install -r requirements.txt",
    "cd frontend/dashboard && npm install"
]

[phases.build]
cmds = [
    "cd frontend/dashboard && npm run build",
    "rm -rf static/*",
    "cp -r frontend/dashboard/build/* static/",
    "cp static/index.html templates/index.html"
]

[start]
cmd = "source /opt/venv/bin/activate && gunicorn app:app --bind 0.0.0.0:$PORT"