[phases.setup]
nixPkgs = ["nodejs", "python3"]

[phases.install]
cmds = [
    "python3 -m pip install --user -r requirements.txt",
    "cd frontend/dashboard && npm install"
]

[phases.build]
cmds = [
    "cd frontend/dashboard && npm run build",
    "cp -r frontend/dashboard/build/* static/"
]

[start]
cmd = "python3 -m gunicorn app:app --bind 0.0.0.0:$PORT"